// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARCEfG-8fnGIgtFtBHByAMb7rWya7of2I',
    appId: '1:626527992113:web:557c2b3ac7392787391810',
    messagingSenderId: '626527992113',
    projectId: 'flutter-chat-app-cd2b8',
    authDomain: 'flutter-chat-app-cd2b8.firebaseapp.com',
    storageBucket: 'flutter-chat-app-cd2b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwZD1Dqbj-fsdAPNI8PLDw8GZD5AXOotg',
    appId: '1:626527992113:android:10c2736f8d7adf23391810',
    messagingSenderId: '626527992113',
    projectId: 'flutter-chat-app-cd2b8',
    storageBucket: 'flutter-chat-app-cd2b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCILc-yEq7ir4VJon3K8k2HyhoBYlDvaWU',
    appId: '1:626527992113:ios:8bfa2bcce6ac7cf1391810',
    messagingSenderId: '626527992113',
    projectId: 'flutter-chat-app-cd2b8',
    storageBucket: 'flutter-chat-app-cd2b8.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARCEfG-8fnGIgtFtBHByAMb7rWya7of2I',
    appId: '1:626527992113:web:a72b950da21b1554391810',
    messagingSenderId: '626527992113',
    projectId: 'flutter-chat-app-cd2b8',
    authDomain: 'flutter-chat-app-cd2b8.firebaseapp.com',
    storageBucket: 'flutter-chat-app-cd2b8.firebasestorage.app',
  );

}