// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/database/models/folder-model.dart';
import 'core/database/models/note-model.dart';
import 'core/database/models/tag-model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8130061655941111807),
    name: 'FolderModel',
    lastPropertyId: const obx_int.IdUid(6, 5346321948630794360),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2708070151618778393),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3563647276379873098),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 9204931513243072754),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5748832961948974354),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 4065387705634208994),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5623097834395097241),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9026921203004506579),
        name: 'color',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5346321948630794360),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 505399610510049400),
    name: 'NoteModel',
    lastPropertyId: const obx_int.IdUid(12, 1964185158960972227),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8239946472854426239),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7199622197681342039),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 3795511921756032326),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4952395897594187084),
        name: 'title',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 2743102382234939992),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 123512426733187090),
        name: 'plainContent',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 3544425815693812420),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7634511429781931119),
        name: 'richContent',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8573007327920044468),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 9192503776778847944),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7517734406889091391),
        name: 'isPinned',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4251519495533624626),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8807279059011295416),
        name: 'color',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 503832966022260181),
        name: 'folderUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1964185158960972227),
        name: 'tagUuids',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8541023260958132737),
    name: 'TagModel',
    lastPropertyId: const obx_int.IdUid(4, 166304622642470407),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7384646637315560312),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2374286917788752084),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(6, 1701395332684960862),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2325903501850238328),
        name: 'name',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(7, 6301797620255430184),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 166304622642470407),
        name: 'color',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 8541023260958132737),
    lastIndexId: const obx_int.IdUid(7, 6301797620255430184),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FolderModel: obx_int.EntityDefinition<FolderModel>(
      model: _entities[0],
      toOneRelations: (FolderModel object) => [],
      toManyRelations: (FolderModel object) => {},
      getId: (FolderModel object) => object.id,
      setId: (FolderModel object, int id) {
        object.id = id;
      },
      objectToFB: (FolderModel object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final iconOffset = fbb.writeString(object.icon);
        final colorOffset = fbb.writeString(object.color);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, iconOffset);
        fbb.addOffset(4, colorOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = FolderModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..uuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..icon = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..color = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          );

        return object;
      },
    ),
    NoteModel: obx_int.EntityDefinition<NoteModel>(
      model: _entities[1],
      toOneRelations: (NoteModel object) => [],
      toManyRelations: (NoteModel object) => {},
      getId: (NoteModel object) => object.id,
      setId: (NoteModel object, int id) {
        object.id = id;
      },
      objectToFB: (NoteModel object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final titleOffset = fbb.writeString(object.title);
        final plainContentOffset = fbb.writeString(object.plainContent);
        final richContentOffset = fbb.writeString(object.richContent);
        final colorOffset = fbb.writeString(object.color);
        final folderUuidOffset = object.folderUuid == null
            ? null
            : fbb.writeString(object.folderUuid!);
        final tagUuidsOffset = fbb.writeString(object.tagUuids);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, plainContentOffset);
        fbb.addOffset(4, richContentOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(7, object.isPinned);
        fbb.addBool(8, object.isDeleted);
        fbb.addOffset(9, colorOffset);
        fbb.addOffset(10, folderUuidOffset);
        fbb.addOffset(11, tagUuidsOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = NoteModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..uuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..title = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..plainContent = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..richContent = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
          )
          ..isPinned = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            18,
            false,
          )
          ..isDeleted = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            20,
            false,
          )
          ..color = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 22, '')
          ..folderUuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 24)
          ..tagUuids = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 26, '');

        return object;
      },
    ),
    TagModel: obx_int.EntityDefinition<TagModel>(
      model: _entities[2],
      toOneRelations: (TagModel object) => [],
      toManyRelations: (TagModel object) => {},
      getId: (TagModel object) => object.id,
      setId: (TagModel object, int id) {
        object.id = id;
      },
      objectToFB: (TagModel object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final colorOffset = fbb.writeString(object.color);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, colorOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = TagModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..uuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..color = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '');

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FolderModel] entity fields to define ObjectBox queries.
class FolderModel_ {
  /// See [FolderModel.id].
  static final id = obx.QueryIntegerProperty<FolderModel>(
    _entities[0].properties[0],
  );

  /// See [FolderModel.uuid].
  static final uuid = obx.QueryStringProperty<FolderModel>(
    _entities[0].properties[1],
  );

  /// See [FolderModel.name].
  static final name = obx.QueryStringProperty<FolderModel>(
    _entities[0].properties[2],
  );

  /// See [FolderModel.icon].
  static final icon = obx.QueryStringProperty<FolderModel>(
    _entities[0].properties[3],
  );

  /// See [FolderModel.color].
  static final color = obx.QueryStringProperty<FolderModel>(
    _entities[0].properties[4],
  );

  /// See [FolderModel.createdAt].
  static final createdAt = obx.QueryDateProperty<FolderModel>(
    _entities[0].properties[5],
  );
}

/// [NoteModel] entity fields to define ObjectBox queries.
class NoteModel_ {
  /// See [NoteModel.id].
  static final id = obx.QueryIntegerProperty<NoteModel>(
    _entities[1].properties[0],
  );

  /// See [NoteModel.uuid].
  static final uuid = obx.QueryStringProperty<NoteModel>(
    _entities[1].properties[1],
  );

  /// See [NoteModel.title].
  static final title = obx.QueryStringProperty<NoteModel>(
    _entities[1].properties[2],
  );

  /// See [NoteModel.plainContent].
  static final plainContent = obx.QueryStringProperty<NoteModel>(
    _entities[1].properties[3],
  );

  /// See [NoteModel.richContent].
  static final richContent = obx.QueryStringProperty<NoteModel>(
    _entities[1].properties[4],
  );

  /// See [NoteModel.createdAt].
  static final createdAt = obx.QueryDateProperty<NoteModel>(
    _entities[1].properties[5],
  );

  /// See [NoteModel.updatedAt].
  static final updatedAt = obx.QueryDateProperty<NoteModel>(
    _entities[1].properties[6],
  );

  /// See [NoteModel.isPinned].
  static final isPinned = obx.QueryBooleanProperty<NoteModel>(
    _entities[1].properties[7],
  );

  /// See [NoteModel.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<NoteModel>(
    _entities[1].properties[8],
  );

  /// See [NoteModel.color].
  static final color = obx.QueryStringProperty<NoteModel>(
    _entities[1].properties[9],
  );

  /// See [NoteModel.folderUuid].
  static final folderUuid = obx.QueryStringProperty<NoteModel>(
    _entities[1].properties[10],
  );

  /// See [NoteModel.tagUuids].
  static final tagUuids = obx.QueryStringProperty<NoteModel>(
    _entities[1].properties[11],
  );
}

/// [TagModel] entity fields to define ObjectBox queries.
class TagModel_ {
  /// See [TagModel.id].
  static final id = obx.QueryIntegerProperty<TagModel>(
    _entities[2].properties[0],
  );

  /// See [TagModel.uuid].
  static final uuid = obx.QueryStringProperty<TagModel>(
    _entities[2].properties[1],
  );

  /// See [TagModel.name].
  static final name = obx.QueryStringProperty<TagModel>(
    _entities[2].properties[2],
  );

  /// See [TagModel.color].
  static final color = obx.QueryStringProperty<TagModel>(
    _entities[2].properties[3],
  );
}
